#ifndef dates_h
#define dates_h

//the entire header file

struct NodeDate {
	String day;
	unsigned long wait; //delta between collor change in millis
	CRGB pattern[12];
};

NodeDate NodeDates[10];

//New Years
NodeDates[0] = {"12-31", 5000, {CRGB::WHITE, CRGB::BLUE, CRGB::GREEN, CRGB::GOLD, CRGB::PINK, CRGB::YELLOW, CRGB::PURPLE, CRGB::CYAN, CRGB::ORANGE, CRGB::RED}};
NodeDates[1] = {"1-1", 5000, {CRGB::WHITE, CRGB::GREEN, CRGB::BLUE, CRGB::GOLD, CRGB::PINK, CRGB::YELLOW, CRGB::RED, CRGB::WHITE, CRGB::ORANGE, CRGB::PURPLE}};

//Independance Day
NodeDates[2] = {"7-4", 2000, {CRGB::RED, CRGB::WHITE, CRGB::BLUE, CRGB::RED, CRGB::WHITE, CRGB::BLUE, CRGB::RED, CRGB::WHITE, CRGB::BLUE, CRGB::RED, CRGB::WHITE, CRGB::BLUE}};

//Pi Day
NodeDates[3] = {"3-14", 3141, {CRGB::GREEN, CRGB::YELLOW, CRGB::BLUE, CRGB::BLACK, CRGB::CYAN, CRGB::BLUE, CRGB::PINK, CRGB::BLACK, CRGB::PURPLE, CRGB::YELLOW, CRGB::ORANGE, CRGB::BLACK}};

//May the 4th
NodeDates[4] = {"5-4", 15000, {CRGB::RED, CRGB::BLUE, CRGB::BLACK, CRGB::BLUE, CRGB::BLACK, CRGB::RED, CRGB::BLUE, CRGB::RED, CRGB::BLACK, CRGB::BLUE, CRGB::RED, CRGB::BLACK}};

//First Contact Day
NodeDates[5] = {"4-5", 8500, {CRGB::GOLD, CRGB::RED, CRGB::BLUE, CRGB::GREEN, CRGB::GOLD, CRGB::RED, CRGB::BLUE, CRGB::GREEN, CRGB::GOLD, CRGB::RED, CRGB::BLUE, CRGB::GREEN}};

//Halloween
NodeDates[6] = {"10-31", 18500, {CRGB::ORANGE, CRGB::BLACK, CRGB::WHITE, CRGB::PURPLE, CRGB::ORANGE, CRGB::BLACK, CRGB::WHITE, CRGB::PURPLE, CRGB::ORANGE, CRGB::BLACK, CRGB::WHITE, CRGB::PURPLE}};

//Valentine's Day
NodeDates[7] = {"2-14", 15000, {CRGB::RED, CRGB::WHITE, CRGB::PINK, CRGB::RED, CRGB::WHITE, CRGB::PINK, CRGB::RED, CRGB::WHITE, CRGB::PINK, CRGB::RED, CRGB::WHITE, CRGB::PINK}};

//Node Incorporation Day
//setup typedef for NodeBlue color
NodeDates[8] = {"7-16", 6000, {CRGB::BLUE, CRGB::WHITE, CRGB::BLUE, CRGB::WHITE, CRGB::BLUE, CRGB::WHITE, CRGB::BLUE, CRGB::WHITE, CRGB::BLUE, CRGB::WHITE, CRGB::BLUE, CRGB::WHITE}};

//Judgement Day
NodeDates[9] = {"8-19", 10000, {CRGB::LIGHTBLUE, CRGB::BLUE, CRGB::DARKBLUE, CRGB::CYAN, CRGB::CADETBLUE, CRGB::LIGHTSTEELBLUE, CRGB::MEDIUMBLUE, CRGB::LIGHTSKYBLUE, CRGB::TURQUOISE, CRGB::SKYBLUE, CRGB::ROYALBLUE, CRGB::NAVY}};

//Add even nerdier obscure references here

#endif
